import XCTest
#if SWIFT_PACKAGE
@testable import SentinelCore
#else
@testable import OpenAIUsageSentinel
#endif

final class SentinelTests: XCTestCase {
    let now = Date(timeIntervalSince1970: 1791000000)
    func testScenario1Scheduled() { let event = DemoScenarios.run(1, now: now).first!; XCTAssertEqual(event.type, .scheduled); XCTAssertFalse(NotificationPolicy.shouldNotify(event, settings: AppSettings(), now: now)) }
    func testScenario2Unexpected() { let event = DemoScenarios.run(2, now: now).first!; XCTAssertEqual(event.type, .accountUnexpected); XCTAssertTrue(event.ownAccountReset); XCTAssertTrue(NotificationPolicy.shouldNotify(event, settings: AppSettings(), now: now)) }
    func testScenario3TwoReddit() { let events = DemoScenarios.run(3, now: now); XCTAssertEqual(events.count, 1); XCTAssertEqual(events[0].level, .early); XCTAssertEqual(events[0].reportCount, 2); XCTAssertTrue(NotificationPolicy.shouldNotify(events[0], settings: AppSettings(), now: now)) }
    func testScenario4Likely() { let events = DemoScenarios.run(4, now: now); XCTAssertEqual(events.count, 1); XCTAssertEqual(events[0].level, .likely); XCTAssertTrue(events[0].ownAccountReset); XCTAssertEqual(events[0].reportCount, 11) }
    func testScenario5Official() { let event = DemoScenarios.run(5, now: now).first!; XCTAssertEqual(event.level, .confirmed); XCTAssertEqual(event.type, .automaticGlobal); XCTAssertEqual(event.confidence, 0.95) }
    func testUnknownResetTimeDoesNotAssertUnexpected() { var before = DemoScenarios.usage(23, at: now.addingTimeInterval(-300), resetAt: now.addingTimeInterval(86400)); before.buckets[0].resetAt = nil; let after = DemoScenarios.usage(100, at: now, resetAt: now.addingTimeInterval(86400)); XCTAssertEqual(PersonalResetDetector.detect(before: before, after: after).first?.type, .unknown) }
    func testUsesOldScheduleNotNewSchedule() { let before = DemoScenarios.usage(23, at: now.addingTimeInterval(-300), resetAt: now.addingTimeInterval(-60)); let after = DemoScenarios.usage(100, at: now, resetAt: now.addingTimeInterval(7*86400)); XCTAssertEqual(PersonalResetDetector.detect(before: before, after: after).first?.type, .scheduled) }
    func testPurchasedIntent() { let before = DemoScenarios.usage(20, at: now.addingTimeInterval(-300), resetAt: now.addingTimeInterval(86400)); let after = DemoScenarios.usage(100, at: now, resetAt: now.addingTimeInterval(7*86400)); XCTAssertEqual(PersonalResetDetector.detect(before: before, after: after, intent: ResetIntent(type: .purchased, recordedAt: now.addingTimeInterval(-60))).first?.type, .purchased) }
    func testBankedIntent() { let before = DemoScenarios.usage(20, at: now.addingTimeInterval(-300), resetAt: now.addingTimeInterval(86400)); let after = DemoScenarios.usage(100, at: now, resetAt: now.addingTimeInterval(7*86400)); XCTAssertEqual(PersonalResetDetector.detect(before: before, after: after, intent: ResetIntent(type: .banked, recordedAt: now.addingTimeInterval(-60))).first?.type, .banked) }
    func testExpiredIntentDoesNotSuppress() { let before = DemoScenarios.usage(20, at: now.addingTimeInterval(-300), resetAt: now.addingTimeInterval(86400)); let after = DemoScenarios.usage(100, at: now, resetAt: now.addingTimeInterval(7*86400)); XCTAssertEqual(PersonalResetDetector.detect(before: before, after: after, intent: ResetIntent(type: .banked, recordedAt: now.addingTimeInterval(-3600))).first?.type, .accountUnexpected) }
    func testAccountSwitchNotReset() { let before = DemoScenarios.usage(20, at: now.addingTimeInterval(-300), resetAt: now.addingTimeInterval(86400)); var after = DemoScenarios.usage(100, at: now, resetAt: now.addingTimeInterval(86400)); after.accountFingerprint = "other"; XCTAssertTrue(PersonalResetDetector.detect(before: before, after: after).isEmpty) }
    func testPlanSwitchNotReset() { let before = DemoScenarios.usage(20, at: now.addingTimeInterval(-300), resetAt: now.addingTimeInterval(86400)); var after = DemoScenarios.usage(100, at: now, resetAt: now.addingTimeInterval(86400)); after.plan = "pro"; XCTAssertTrue(PersonalResetDetector.detect(before: before, after: after).isEmpty) }
    func testNoAlertOnNormalConsumption() { let before = DemoScenarios.usage(30, at: now.addingTimeInterval(-300), resetAt: now.addingTimeInterval(86400)); let after = DemoScenarios.usage(20, at: now, resetAt: now.addingTimeInterval(86400)); XCTAssertTrue(PersonalResetDetector.detect(before: before, after: after).isEmpty) }
    func testDuplicateTextDoesNotInflate() { var signals = DemoScenarios.reports(2, platform: "Reddit", now: now); signals[1].source.title = signals[0].source.title; signals[1].source.snippet = signals[0].source.snippet; XCTAssertEqual(EventEngine.uniqueSources(signals.map(\.source)).count, 1) }
    func testDuplicateAuthorDoesNotInflate() { var signals = DemoScenarios.reports(4, platform: "Reddit", now: now); for i in signals.indices { signals[i].source.author = "same" }; XCTAssertEqual(EventEngine.uniqueSources(signals.map(\.source)).count, 1) }
    func testAgeDecay() { XCTAssertEqual(EventEngine.ageWeight(now.addingTimeInterval(-7200), now: now), 0.9); XCTAssertEqual(EventEngine.ageWeight(now.addingTimeInterval(-90000), now: now), 0.25); XCTAssertEqual(EventEngine.ageWeight(nil, now: now), 0.25) }
    func testOldPostsNotTodayEvents() { let signals = DemoScenarios.reports(3, platform: "Reddit", now: now.addingTimeInterval(-90000)); XCTAssertTrue(EventEngine.merge(signals: signals, personal: [], into: [], now: now).isEmpty) }
    func testNoRepeatWithinConfidenceLevel() { var event = DemoScenarios.run(3, now: now)[0]; event.notifiedRank = event.level.rank; event.confidence = 0.38; XCTAssertFalse(NotificationPolicy.shouldNotify(event, settings: AppSettings(), now: now)); event.confidence = 0.7; XCTAssertTrue(NotificationPolicy.shouldNotify(event, settings: AppSettings(), now: now)) }
    func testOwnResetRenotifies() { var event = DemoScenarios.run(4, now: now)[0]; event.notifiedRank = event.level.rank; XCTAssertTrue(NotificationPolicy.shouldNotify(event, settings: AppSettings(), now: now)); event.notifiedOwnReset = true; XCTAssertFalse(NotificationPolicy.shouldNotify(event, settings: AppSettings(), now: now)) }
    func testCommunityCannotBeConfirmed() { XCTAssertLessThan(DemoScenarios.run(4, now: now)[0].confidence, 0.9) }
    func testProductSegmentation() { var signals = DemoScenarios.reports(2, platform: "Reddit", now: now); signals[1].product = "ChatGPT Work"; XCTAssertEqual(EventEngine.merge(signals: signals, personal: [], into: [], now: now).count, 2) }
    func testWaveDetection() { XCTAssertNotNil(EventEngine.waveDescription(DemoScenarios.run(4, now: now)[0])) }
    func testMissingWindowNotInvented() throws { let result: [String: Any] = ["rateLimits": ["limitId": "codex", "secondary": ["usedPercent": 39, "windowDurationMins": 10080, "resetsAt": now.timeIntervalSince1970+3600]]]; let state = try CodexCLIUsageProvider.parse(result, now: now); XCTAssertEqual(state.buckets.count, 1); XCTAssertEqual(state.buckets[0].remainingPercent, 61); XCTAssertEqual(state.buckets[0].name, "Weekly") }
    func testMissingPercentageNotZero() { XCTAssertThrowsError(try CodexCLIUsageProvider.parse(["rateLimits": ["primary": ["windowDurationMins": 300]]], now: now)) }
    func testMultipleBuckets() throws { let result: [String: Any] = ["rateLimitsByLimitId": ["codex": ["primary": ["usedPercent": 28, "windowDurationMins": 300]], "future": ["limitName": "Future", "primary": ["usedPercent": 15, "windowDurationMins": 60]]]]; let state = try CodexCLIUsageProvider.parse(result, now: now); XCTAssertEqual(state.buckets.count, 2); XCTAssertNil(state.buckets[0].resetAt); XCTAssertEqual(state.buckets[1].product, "Future") }
    func testGitHubIssueNotOfficial() { XCTAssertEqual(DemoScenarios.reports(1, platform: "GitHub", now: now)[0].source.official, false) }
    func testNegativeComplaintIgnored() { var source = DemoScenarios.reports(1, platform: "GitHub", now: now)[0].source; source.title = "My Codex weekly limit did not reset"; source.snippet = "quota reset isn't working"; XCTAssertNil(SignalClassifier.classify(source)) }
    func testBankedDifferentFromGlobal() { var source = DemoScenarios.reports(1, platform: "GitHub", now: now)[0].source; source.title = "My Codex banked reset offered"; source.snippet = "free reset"; XCTAssertEqual(SignalClassifier.classify(source)?.behavior, .banked) }
    func testRSSAndAtomDatesAndLinks() throws { let xml = "<feed><entry><title>My Codex quota reset</title><author><name>alice</name></author><link href='https://example.com/a'/><published>2026-10-03T01:00:00Z</published><content type='html'>&lt;p&gt;My quota returned to 100%&lt;/p&gt;</content></entry></feed>"; let result = try FeedParser.parse(Data(xml.utf8)); XCTAssertEqual(result.count, 1); XCTAssertEqual(result[0].author, "alice"); XCTAssertNotNil(result[0].date); XCTAssertEqual(result[0].url, "https://example.com/a"); XCTAssertTrue(FeedParser.plainText(result[0].content).contains("100%")) }
    func testPersistenceRoundTripAndRetention() throws { let root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString); defer { try? FileManager.default.removeItem(at: root) }; let db = try LocalDatabase(url: root.appendingPathComponent("test.sqlite")); let old = DemoScenarios.usage(20, at: now.addingTimeInterval(-36*86400), resetAt: now); let recent = DemoScenarios.usage(37, at: now.addingTimeInterval(-30*86400), resetAt: now); try db.append(old, now: now); try db.append(recent, now: now); XCTAssertEqual(try db.snapshots().count, 1); let events = DemoScenarios.run(3, now: now); try db.save(events, key: "events"); XCTAssertEqual(try db.load([ResetEvent].self, key: "events"), events) }
    func testLiveCodexWhenRequested() async throws { guard ProcessInfo.processInfo.environment["SENTINEL_LIVE_TEST"] == "1" else { throw XCTSkip("Set SENTINEL_LIVE_TEST=1 for authorized live local Codex read.") }; let state = try await CodexCLIUsageProvider().fetchUsage(); XCTAssertFalse(state.buckets.isEmpty); XCTAssertTrue(state.buckets.allSatisfy { $0.remainingPercent >= 0 && $0.remainingPercent <= 100 }); print("LIVE CODEX: " + state.buckets.map { "\($0.name) \(Int($0.remainingPercent))%" }.joined(separator: ", ")) }
    func testGlobalTitleNotMisclassifiedByBankedMention() { var source = DemoScenarios.reports(1, platform: "GitHub", now: now)[0].source; source.title = "Codex global reset did not reach my account"; source.snippet = "The global reset was announced. A banked reset is a different mechanism, not to have been applied to my account."; let signal = SignalClassifier.classify(source); XCTAssertEqual(signal?.behavior, .suspectedGlobal); XCTAssertEqual(signal?.isFirsthand, false) }
    func testNearFullResetStillDetected() { let before = DemoScenarios.usage(97, at: now.addingTimeInterval(-300), resetAt: now.addingTimeInterval(86400)); let after = DemoScenarios.usage(100, at: now, resetAt: now.addingTimeInterval(86400)); XCTAssertEqual(PersonalResetDetector.detect(before: before, after: after).first?.type, .accountUnexpected) }
    func testLocalNewsSourcesWhenRequested() async throws {
        guard ProcessInfo.processInfo.environment["SENTINEL_LIVE_TEST"] == "1" else { throw XCTSkip("Optional live public source integration test.") }
        let sources: [any ResetSignalSource] = [GitHubCodexSource(), RedditSource(), OpenAIStatusSource(), OpenAIReleaseNotesSource()]
        for source in sources {
            let result = try await source.fetchSignals()
            XCTAssertTrue(result.allSatisfy { !$0.source.url.absoluteString.isEmpty })
            print("LIVE SOURCE: \(source.name) OK · \(result.count) matching entries (freshness filtered by engine)")
        }
    }

    func testExplicitRegularReportIgnored() { var source = DemoScenarios.reports(1, platform: "Reddit", now: now)[0].source; source.title = "My Codex quota reset at the scheduled reset"; source.snippet = "My weekly allowance back to 100% as usual"; XCTAssertNil(SignalClassifier.classify(source)) }

    func testDecreasedCreditsRemainAmbiguous() { let before = DemoScenarios.usage(20, at: now.addingTimeInterval(-300), resetAt: now.addingTimeInterval(86400)); var after = DemoScenarios.usage(100, at: now, resetAt: now.addingTimeInterval(86400)); after.resetCredits = 1; let event = PersonalResetDetector.detect(before: before, after: after).first!; XCTAssertEqual(event.type, .unknown); XCTAssertFalse(event.ownAccountReset) }

}
